#!/usr/bin/env python3
"""Generate the deterministic OpenGym catalogue seed migration from its JSON source."""

from __future__ import annotations

import json
from collections.abc import Iterable
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data" / "opengym" / "exercises.json"
DESTINATION = ROOT / "migrations" / "011_strength_exercise_catalog.sql"

MUSCLE_ALIASES = {
    "abs": "abs", "core": "abs", "abdominals": "abs", "lower abs": "abs",
    "pectorals": "chest", "chest": "chest", "upper chest": "chest",
    "biceps": "biceps", "brachialis": "biceps",
    "glutes": "gluteal", "abductors": "gluteal",
    "delts": "deltoids", "shoulders": "deltoids", "deltoids": "deltoids",
    "rear deltoids": "deltoids", "rotator cuff": "deltoids",
    "triceps": "triceps",
    "upper back": "upper-back", "lats": "upper-back", "rhomboids": "upper-back",
    "back": "upper-back", "latissimus dorsi": "upper-back",
    "calves": "calves", "soleus": "calves", "quads": "quadriceps",
    "quadriceps": "quadriceps", "forearms": "forearm", "wrists": "forearm",
    "wrist flexors": "forearm", "wrist extensors": "forearm", "grip muscles": "forearm",
    "hamstrings": "hamstring", "spine": "lower-back", "lower back": "lower-back",
    "traps": "trapezius", "trapezius": "trapezius", "levator scapulae": "trapezius",
    "adductors": "adductors", "groin": "adductors", "inner thighs": "adductors",
    "serratus anterior": "serratus", "hip flexors": "hip-flexors", "obliques": "obliques",
    "shins": "tibialis",
}

BODY_PART_FALLBACKS = {
    "chest": {"chest": 1}, "back": {"upper-back": 0.75, "lower-back": 0.25},
    "shoulders": {"deltoids": 1}, "upper arms": {"biceps": 0.5, "triceps": 0.5},
    "lower arms": {"forearm": 1}, "waist": {"abs": 0.7, "obliques": 0.3},
    "upper legs": {"quadriceps": 0.4, "hamstring": 0.35, "gluteal": 0.25},
    "lower legs": {"calves": 0.8, "tibialis": 0.2}, "neck": {"trapezius": 1},
}


def sql(value: object) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def muscle_rows(exercise: dict) -> Iterable[tuple[str, float]]:
    values: dict[str, float] = {}
    primary = MUSCLE_ALIASES.get(exercise.get("tg", "").strip().lower())
    if primary:
        values[primary] = 1
    for name in exercise.get("sm", []):
        muscle = MUSCLE_ALIASES.get(name.strip().lower())
        if muscle:
            values[muscle] = max(values.get(muscle, 0), 0.4)
    if not values:
        values = BODY_PART_FALLBACKS.get(exercise.get("bp", ""), {})
    return values.items()


def chunks(rows: list[tuple], size: int = 400) -> Iterable[list[tuple]]:
    for start in range(0, len(rows), size):
        yield rows[start : start + size]


def values(rows: list[tuple]) -> str:
    return ",\n".join(f"    ({', '.join(sql(value) for value in row)})" for row in rows)


def main() -> None:
    exercises = json.loads(SOURCE.read_text(encoding="utf-8"))
    lines = ["-- Generated by scripts/generate_opengym_catalog_migration.py. Do not edit manually.", ""]
    exercise_rows: list[tuple] = []
    instruction_rows: list[tuple] = []
    muscle_rows_to_insert: list[tuple] = []

    for exercise in exercises:
        exercise_rows.append(
            (
                exercise["id"], exercise["n"], exercise["bp"], exercise["eq"], exercise["tg"],
                "opengym/v1/images/" + exercise["img"],
                "opengym/v1/gifs/" + exercise["gif"] if exercise.get("gif") else None,
                True,
            )
        )
        for position, instruction in enumerate(exercise.get("st", [])):
            instruction_rows.append((exercise["id"], position, instruction))
        for muscle, factor in muscle_rows(exercise):
            muscle_rows_to_insert.append((exercise["id"], muscle, factor))

    for batch in chunks(exercise_rows):
        lines.extend(
            [
                "INSERT INTO strength_exercises (id, name, body_part, equipment, target_muscle, image_key, gif_key, is_catalog)",
                "VALUES",
                values(batch),
                "ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, body_part = EXCLUDED.body_part, equipment = EXCLUDED.equipment, target_muscle = EXCLUDED.target_muscle, image_key = EXCLUDED.image_key, gif_key = EXCLUDED.gif_key, is_catalog = TRUE, archived_at = NULL;",
                "",
            ]
        )

    for batch in chunks(instruction_rows):
        lines.extend(
            [
                "INSERT INTO strength_exercise_instructions (exercise_id, position, instruction)",
                "VALUES",
                values(batch),
                "ON CONFLICT (exercise_id, position) DO UPDATE SET instruction = EXCLUDED.instruction;",
                "",
            ]
        )

    for batch in chunks(muscle_rows_to_insert):
        lines.extend(
            [
                "INSERT INTO strength_exercise_muscles (exercise_id, muscle_key, load_factor)",
                "VALUES",
                values(batch),
                "ON CONFLICT (exercise_id, muscle_key) DO UPDATE SET load_factor = EXCLUDED.load_factor;",
                "",
            ]
        )
    DESTINATION.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {DESTINATION.relative_to(ROOT)} for {len(exercises)} exercises.")


if __name__ == "__main__":
    main()
